### ISSUE TITLE
support the server and client mode

### ISSUE THREAD

**Issue by newcuit** [OpenCloudOS/lkp-extent#2]
The traditional LKP is to run tests on Linux, but here, we need to make some adjustments.
Sometimes, we need to test multiple servers, so we need one pc as a server and other machines as clients. The tester sends control commands to other clients by typing commands through the server. After receiving the command, the client executes the specified command. eg, server A receives a command to execute 100 container memory violence tests and server B receives a command to execute 50 container disk violence tests.
At last, the server can receive the test results from the client.

Note that, server can also execute some test cases from itself.

**Comment by BIGWJZ** [comment]
**Now the lkp-extent supports Server/Client mode**
1. Both Server and Client can run lkp-test
2. Server can send commands to clients and control them run specific testcase of lkp-tests
3. Server can push new testcases and request results of clietns
